### ISSUE TITLE
workbench 구성

### ISSUE THREAD

**Issue by hughesgoon** [osamhack2020/Cloud_BlurPencil_GonNyong4#28]
## workbench 구성
파일 업로드부터 모자이크까지 이어지는 기능 타임라인 구현을 위한 의견 통합 이슈입니다.

#26 에서 말해주셨듯 실질적인 구현을 위한 구성을 다시 통합하고자 합니다.
> 사진 올리고, 객체를 선택하도록 하는 버튼같은게 있어야 할지, upload에서 유저가 select해야할 게 모두 무엇인가
> 이미지 업로드 이후 유저가 할 수 있는 행동과 서버에서 해줄수 있는 행동을 정리해보면 좋을 것 같다.

개인적으로 고민해본 내용은 아래와 같습니다.

1. [유저] 이미지를 업로드합니다.
2. [서버] (허용된 파일이라면) 파일을 업로드하고 객체 인식 API로 POST합니다.
3. [서버] 인식된 객체 정보를 json으로 받고, 사용자의 이미지와 객체들을 표시합니다.
  - 이때 (선택이 되어있는) 객체들의 bounded box를 이미지 상단에 표시합니다.
  - 인식된 객체들을 Crop된 이미지(bounded box와 각각 연결되어있음)로 표시해줍니다.(우선순위 下, 일단 이미지 위에서 클릭만 하는 식이어도 기능상 문제없을듯)
  - bounded box 또는 Crop된 이미지는 clickable하며 하나의 체크박스처럼 작동됩니다.
4. [유저] 유저는 표시되는 객체들 중 원하는 객체들만 선택합니다.
5. [서버] 선택된 객체들의 좌표와 이미지를 다시 API로 POST합니다.
6. [서버] 최종 모자이크된 이미지를 반환합니다.

결론적으로 유저는 파일을 업로드한 뒤, 표시된 box를 선택하는 작업만 하면 되지 않을까 생각합니다.
#27 과 [제안해주신 예시](https://github.com/orgs/osamhack2020/teams/gonnyong4/discussions/10)처럼 진행 단계를 상단에 표시하고, 객체 정보는 우측 패널에 표시되면 깔끔하지 않을까요?

유저의 선택을 조금 더 줄이거나, 최종 결과물을 본 이후의 기능같은부분이 추가로 필요할까요?
아니면 저 순서에서 API를 개선할 방법이 있을가요?

**Comment by kyechan99** [comment]
일단 블러 처리 과정이 다음과 같나요?
1. 서버가 이미지를 받고 파이토치로 보냄
2. 파이가 이미지에서 인식된 객체들을 서버로 json 보냄
3. 서버가 클라로 json 위치에 해당한 이미지들을 인식했다고 알려줌
4. 유저가 이 위치는 인식하고 싶지 않다고 캔슬함
5. 서버가 파이토치API 로 포함된 json 위치값들을 보냄
6. 파이가 서버로 해당된 위치값들을 블러해서 사진을 보냄
7. 서버가 클라로 사진을 보냄

**Comment by seungpyo** [comment]
강예찬님이 말씀하신 대로입니다. 정리하자면 아래 그림과 같습니다.
![image](https://user-images.githubusercontent.com/7239579/96877750-01658a80-14b5-11eb-9fe7-118d594dc8a7.png)

위 그림은 아래 링크에서 수정하실 수 있습니다.
https://docs.google.com/presentation/d/1ooRDpUpMLkj_jx2sO44OcsdAr6wxBwOuzB4tiZnJhMI/edit?usp=sharing

블러처리 API는 이번주중으로 구현해서 PR 올리겠습니다.

**Comment by westofsky** [comment]
우측 패널 정말 좋다고생각합니다. 혹시근데 이미지를 선택하면서 동시에 우측패널에서 객체 정보 선택하는 작업도 같이 할 수 있나요 ???

**Comment by kyechan99** [comment]
> 혹시근데 이미지를 선택하면서 동시에 우측패널에서 객체 정보 선택하는 작업도 같이 할 수 있나요 ???

중앙 이미지에서 검열된 부분을 누르면 우측에서 어떤 반응이 있는지(?) 같은 말씀이신가요??

**Comment by westofsky** [comment]
> 중앙 이미지에서 검열된 부분을 누르면 우측에서 어떤 반응이 있는지(?) 같은 말씀이신가요??
넵 업로드하고 나서 우측패널에 객체 정보들이 뜰 것이고, 거기서 선택할 수 있는거 맞나요 ?? Client에서 logo Detection server까지 연결돼서 유저가 실시간으로 객체를 선택하고 취소했을때 이미지에 적용할 수 있는지 궁금합니다

**Comment by hughesgoon** [comment]
Select 할때마다 파이토치 서버에 bbox를 보이게하는 API를 호출하는 방식이 아니라

최초의 json 값을 토대로 절대 좌표를 계산해서 bbox 컴포넌트를 클라이언트에 표시하고, 클릭할때마다 css visual 속성을 변화시키면 처리속도도 빨라지고 select 박스와 바인딩도 가능할듯합니다.

**Comment by westofsky** [comment]
> 최초의 json 값을 토대로 절대 좌표를 계산해서 bbox 컴포넌트를 클라이언트에 표시하고, 클릭할때마다 css visual 속성을 변화시키면 처리속도도 빨라지고 select 박스와 바인딩도 가능하지않을까요?

제일 좋은 방법인거같네요.
