### ISSUE TITLE
공유 | 폴더 기능 추가에 대해서

### ISSUE THREAD

**Issue by kyechan99** [osamhack2020/Cloud_BlurPencil_GonNyong4#46]
# 공유 | 폴더 기능 추가에 대해서
추가하게 된 이유는 카톡에서 얘기했는데요.. 일단 구현된 사항은 다음과 같습니다. (한 85%??)
시간이 시간이다 보니 머지에 대해선 고민해 봐야될것같습니다.

### 대시보드
![image](https://user-images.githubusercontent.com/14146566/97700856-d8b24600-1aef-11eb-9bb3-01a20b99193c.png)
> 점선 : 폴더 생성
> 메인색 : 내 폴더
> 연한색 : 공유받은 폴더

### 폴더추가
![image](https://user-images.githubusercontent.com/14146566/97700891-e49e0800-1aef-11eb-8452-0018f9118610.png)

### 파일 데이터 보기 | 파일을 폴더로 이동
![image](https://user-images.githubusercontent.com/14146566/97700936-f54e7e00-1aef-11eb-96df-8db2e5b5023f.png)

### 폴더 공유
![image](https://user-images.githubusercontent.com/14146566/97700967-04cdc700-1af0-11eb-8117-f9a6297c7660.png)
폴더내 파일 항목을 보여주는 방식을` 대시보드->파일들` 형태로 할지 `최근항목->파일들` 형태로 할지 개인적으론 성준님이 ㅈ작해 주셨던 `최근항목->파일들`이 이미지 하나하나를 크게 보여줄 수 있어서 괜찮아 보이긴 한데요..

### 공유 받은 유저 화면
![image](https://user-images.githubusercontent.com/14146566/97701066-3050b180-1af0-11eb-8883-02a3d2379c11.png)

### 미구현된것
- 클라내 폴더 삭제 (API 는 존재)
- 공유된 사용자들 보여주기 (따로 API는 없고 기존 폴더 불러올때 사용자들도 같이 있음)
- 공유된 사용자 해제 (API 아직 없음)

**Comment by westofsky** [comment]
폴더 내 보여주는 건 예찬님이 구현하신대로 폴더 안에서 파일 클릭하면 
![image](https://user-images.githubusercontent.com/15906101/97709505-cb03bd00-1afd-11eb-9520-73bcd3be50bb.png)
이렇게 나오고, 그 안에서 이미지를 클릭하면 이미지만 크게 볼 수 있도록 modal만 띄워도 될거같아요
또 폴던에서 파일들 표시하는건 pagination 대신 스크롤로 구현해도 좋을듯해요
